using System.Text.Json;
using LioConecta.Domain.Entities;
using LioConecta.Domain.Enums;

namespace LioConecta.Infrastructure.Seed;

internal static class ComunicadoCatalogSeed
{
    internal sealed record CatalogEntry(
        Guid Id,
        string Slug,
        ComunicadoKind Kind,
        string Title,
        string Excerpt,
        string HeroImageUrl,
        Guid AuthorId,
        bool IsMandatory,
        DateTimeOffset PublishedAt,
        params string[] Paragraphs);

    internal static readonly CatalogEntry[] Entries =
    [
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc03"),
            "estrategia-2026",
            ComunicadoKind.Oficial,
            "Atualização importante sobre nossa estratégia 2026",
            "Estamos lançando novas iniciativas de colaboração e bem-estar para todos os colaboradores. Leia os detalhes completos e compartilhe com sua equipe.",
            "/bg-announcement.png",
            SeedIds.MariaSilva,
            false,
            new DateTimeOffset(2026, 7, 4, 12, 0, 0, TimeSpan.Zero),
            "A liderança da LioConecta apresenta as diretrizes estratégicas para 2026, com foco em colaboração entre áreas, bem-estar no trabalho e inovação contínua.",
            "Entre as iniciativas estão programas de desenvolvimento, trilhas de carreira revisadas, ações de saúde mental e novos rituais de alinhamento entre times.",
            "Gestores devem socializar este comunicado com suas equipes até sexta-feira e registrar dúvidas no canal oficial de Recursos Humanos."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc04"),
            "seguranca-informacao",
            ComunicadoKind.Oficial,
            "Nova política de segurança da informação",
            "A partir da próxima semana, todos os colaboradores devem atualizar suas senhas e concluir o treinamento obrigatório de segurança.",
            "/bg-comunicado-security.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 7, 2, 12, 0, 0, TimeSpan.Zero),
            "A TI publica a nova política de segurança da informação, alinhada às melhores práticas de mercado e aos requisitos de compliance da empresa.",
            "Todos devem trocar a senha corporativa, revisar permissões de acesso e concluir o módulo de treinamento disponível no portal de serviços.",
            "O não cumprimento até o prazo informado pode resultar em restrições temporárias de acesso a sistemas críticos."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc05"),
            "ferias-coletivas-2026",
            ComunicadoKind.Oficial,
            "Calendário de férias coletivas 2026",
            "Informamos o calendário de férias coletivas para o final do ano. Consulte as datas por unidade e registre sua preferência até sexta-feira.",
            "/bg-benefits.png",
            SeedIds.MariaSilva,
            false,
            new DateTimeOffset(2026, 6, 28, 12, 0, 0, TimeSpan.Zero),
            "O calendário de férias coletivas foi definido em conjunto com a liderança das unidades e está disponível para consulta por área.",
            "Colaboradores elegíveis devem registrar preferências no sistema de RH até sexta-feira às 18h.",
            "Dúvidas sobre elegibilidade ou exceções devem ser encaminhadas ao gestor direto e ao time de Recursos Humanos."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc06"),
            "parcerias-estrategicas-2026",
            ComunicadoKind.Oficial,
            "Novas parcerias estratégicas para 2026",
            "A LioConecta anuncia parcerias que ampliam oportunidades de desenvolvimento e colaboração entre áreas e unidades.",
            "/bg-news.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 6, 20, 12, 0, 0, TimeSpan.Zero),
            "A Diretoria comunica a formalização de novas parcerias estratégicas voltadas a desenvolvimento profissional, inovação e expansão de competências internas.",
            "As iniciativas incluem programas conjuntos com instituições parceiras, trilhas de capacitação e projetos interáreas.",
            "Materiais complementares serão publicados nas próximas semanas no portal de documentos corporativos."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc07"),
            "centro-inovacao",
            ComunicadoKind.Oficial,
            "Inauguração do centro de inovação",
            "O novo centro de inovação e pesquisa aplicada já está em operação. Conheça os espaços, agendas e formas de participação dos times.",
            "/bg-news-innovation.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 6, 12, 12, 0, 0, TimeSpan.Zero),
            "O centro de inovação e pesquisa aplicada foi inaugurado e já recebe times para imersões, hackathons internos e prototipagem de soluções.",
            "As agendas de uso podem ser consultadas no calendário compartilhado e reservadas pelo portal de Facilities.",
            "Times interessados em participar de projetos piloto devem enviar proposta resumida ao comitê de inovação."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc08"),
            "kickoff-campanha-h2",
            ComunicadoKind.Departamental,
            "Kick-off da campanha interna do segundo semestre",
            "O time de Marketing convida todas as áreas para o alinhamento da campanha interna. Participe da reunião e confira o calendário de ações.",
            "/bg-marketing-event.png",
            SeedIds.JuliaSantos,
            false,
            new DateTimeOffset(2026, 7, 3, 12, 0, 0, TimeSpan.Zero),
            "O Marketing convida representantes de todas as áreas para o kick-off da campanha interna do segundo semestre.",
            "A reunião apresentará o calendário de ações, peças de apoio e responsabilidades por departamento.",
            "Confirme a participação do seu time até quarta-feira pelo formulário indicado neste comunicado."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc09"),
            "manutencao-sistemas",
            ComunicadoKind.Departamental,
            "Janela de manutenção dos sistemas internos",
            "No sábado, das 8h às 12h, alguns sistemas ficarão indisponíveis para atualização. Planeje suas atividades com antecedência.",
            "/bg-comunicado-security.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 7, 1, 12, 0, 0, TimeSpan.Zero),
            "A TI informa janela de manutenção programada para atualização de sistemas internos críticos.",
            "Durante o período, ERP, portal de serviços e alguns relatórios ficarão indisponíveis.",
            "Planeje atividades dependentes desses sistemas e acompanhe o status em tempo real no canal oficial de TI."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0a"),
            "onboarding-julho",
            ComunicadoKind.Departamental,
            "Onboarding dos novos colaboradores de julho",
            "Gestores devem confirmar a agenda de integração e indicar padrinhos para os novos membros que chegam na próxima semana.",
            "/bg-benefits.png",
            SeedIds.MariaSilva,
            false,
            new DateTimeOffset(2026, 6, 30, 12, 0, 0, TimeSpan.Zero),
            "Recursos Humanos publica a agenda de integração dos novos colaboradores que iniciam em julho.",
            "Gestores devem confirmar presença nas etapas obrigatórias e indicar padrinhos responsáveis pelo acolhimento.",
            "O checklist completo de onboarding está disponível no portal de Pessoas."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0b"),
            "metas-comercial-julho",
            ComunicadoKind.Departamental,
            "Metas e rituais do time comercial em julho",
            "Confira o novo formato das reuniões semanais, o ranking de indicadores e os materiais de apoio para o ciclo comercial.",
            "/bg-social-coffee.png",
            SeedIds.CarlosMendes,
            false,
            new DateTimeOffset(2026, 6, 27, 12, 0, 0, TimeSpan.Zero),
            "O time Comercial comunica o novo formato das reuniões semanais e as metas do ciclo de julho.",
            "Indicadores, ranking parcial e materiais de apoio foram atualizados na biblioteca do departamento.",
            "Líderes regionais devem revisar o plano com suas equipes até segunda-feira."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0c"),
            "pesquisa-evento-integracao",
            ComunicadoKind.Departamental,
            "Pesquisa de preferências para o evento de integração",
            "O Marketing está coletando sugestões de atividades e horários para o próximo evento de integração entre áreas.",
            "/bg-poll.png",
            SeedIds.JuliaSantos,
            false,
            new DateTimeOffset(2026, 6, 24, 12, 0, 0, TimeSpan.Zero),
            "Marketing abre pesquisa para definir formato, horários e atividades do próximo evento de integração entre áreas.",
            "A participação de todos os colaboradores é importante para equilibrar preferências e logística.",
            "O formulário ficará disponível até o fim da semana no link indicado neste comunicado."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0d"),
            "senha-18h",
            ComunicadoKind.Urgente,
            "Ação imediata: atualize sua senha até às 18h",
            "Identificamos tentativas de acesso indevido. Todos os colaboradores devem trocar a senha corporativa ainda hoje e ativar a autenticação em dois fatores.",
            "/bg-comunicado-security.png",
            SeedIds.JulioSchwartzman,
            true,
            new DateTimeOffset(2026, 7, 4, 12, 15, 0, TimeSpan.Zero),
            "A TI identificou tentativas de acesso indevido e solicita ação imediata de todos os colaboradores.",
            "Atualize sua senha corporativa até às 18h de hoje e ative a autenticação em dois fatores.",
            "Em caso de dificuldade, acione o help desk pelo canal prioritário informado no portal de serviços de TI."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0e"),
            "prazo-documentos-beneficios",
            ComunicadoKind.Urgente,
            "Prazo final para envio de documentos de benefícios",
            "Colaboradores com pendências devem enviar a documentação até amanhã às 12h para não perder a elegibilidade no ciclo atual.",
            "/bg-announcement.png",
            SeedIds.MariaSilva,
            true,
            new DateTimeOffset(2026, 7, 3, 19, 40, 0, TimeSpan.Zero),
            "Recursos Humanos reforça o prazo final para envio de documentação pendente relacionada a benefícios.",
            "Colaboradores com pendências devem anexar os arquivos no portal até amanhã às 12h.",
            "Após o prazo, a elegibilidade no ciclo atual poderá ser suspensa até regularização."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc0f"),
            "vpn-contorno",
            ComunicadoKind.Urgente,
            "Instabilidade no acesso VPN — contorno temporário",
            "Equipes remotas devem usar o link alternativo de acesso enquanto a VPN principal é restabelecida. Previsão de normalização: 14h.",
            "/bg-poll-remote.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 7, 2, 14, 20, 0, TimeSpan.Zero),
            "A TI reporta instabilidade no acesso via VPN principal e disponibiliza contorno temporário para equipes remotas.",
            "Utilize o link alternativo publicado no portal de serviços até a normalização prevista para 14h.",
            "Atualizações serão comunicadas no mesmo canal assim que a operação for restabelecida."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc10"),
            "treinamento-compliance",
            ComunicadoKind.Urgente,
            "Confirmação obrigatória de presença no treinamento de compliance",
            "Quem ainda não confirmou a participação precisa responder até o fim do dia. A lista será enviada à liderança amanhã pela manhã.",
            "/bg-benefits.png",
            SeedIds.MariaSilva,
            true,
            new DateTimeOffset(2026, 7, 1, 11, 5, 0, TimeSpan.Zero),
            "Recursos Humanos solicita confirmação obrigatória de presença no treinamento de compliance.",
            "Colaboradores pendentes devem responder até o fim do dia pelo link oficial.",
            "A lista final será encaminhada à liderança amanhã pela manhã."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc11"),
            "resultados-q1-2026",
            ComunicadoKind.Arquivo,
            "Resultados do primeiro trimestre e prioridades do semestre",
            "Registro do comunicado institucional com o balanço do trimestre e as diretrizes de execução para as áreas.",
            "/bg-news.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 5, 15, 12, 0, 0, TimeSpan.Zero),
            "Comunicado arquivado com o balanço do primeiro trimestre e as prioridades definidas para o semestre.",
            "O documento consolida indicadores, destaques por área e diretrizes de execução.",
            "Mantido no arquivo para consulta histórica e referência em planejamentos futuros."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc12"),
            "migracao-colaboracao",
            ComunicadoKind.Arquivo,
            "Migração concluída do ambiente de colaboração",
            "Comunicado histórico sobre a conclusão da migração de ferramentas e os novos padrões de uso para os times.",
            "/bg-news-innovation.png",
            SeedIds.JulioSchwartzman,
            false,
            new DateTimeOffset(2026, 4, 2, 12, 0, 0, TimeSpan.Zero),
            "Registro histórico da conclusão da migração do ambiente de colaboração corporativa.",
            "O comunicado descreve novos padrões de uso, ferramentas substituídas e canais oficiais de suporte.",
            "Consulte este documento para contexto sobre a transição realizada no primeiro semestre."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc13"),
            "encerramento-2025",
            ComunicadoKind.Arquivo,
            "Encerramento do ano e calendário de recesso",
            "Orientações de recesso, plantões e contatos de emergência publicados no final de 2025.",
            "/bg-celebration.png",
            SeedIds.MariaSilva,
            false,
            new DateTimeOffset(2025, 12, 18, 12, 0, 0, TimeSpan.Zero),
            "Comunicado arquivado com orientações de encerramento do ano e calendário de recesso de 2025.",
            "Inclui informações sobre plantões, contatos de emergência e retorno das atividades.",
            "Mantido para consulta histórica e referência em ciclos futuros."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc14"),
            "evento-integracao-2025",
            ComunicadoKind.Arquivo,
            "Cobertura e materiais do evento anual de integração",
            "Galeria, apresentações e resumo das atividades do evento anual, mantidos para consulta das áreas.",
            "/bg-marketing-event.png",
            SeedIds.JuliaSantos,
            false,
            new DateTimeOffset(2025, 11, 10, 12, 0, 0, TimeSpan.Zero),
            "Arquivo com cobertura, apresentações e resumo das atividades do evento anual de integração.",
            "Materiais permanecem disponíveis para consulta das áreas e onboarding de novos colaboradores.",
            "Solicitações de republicação devem ser feitas ao time de Marketing."),
        new CatalogEntry(
            Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccc15"),
            "pesquisa-clima-2025",
            ComunicadoKind.Arquivo,
            "Resultado da pesquisa de clima organizacional",
            "Síntese dos resultados e planos de ação definidos a partir da pesquisa de clima do segundo semestre de 2025.",
            "/bg-poll.png",
            SeedIds.MariaSilva,
            false,
            new DateTimeOffset(2025, 9, 22, 12, 0, 0, TimeSpan.Zero),
            "Comunicado arquivado com a síntese dos resultados da pesquisa de clima organizacional do segundo semestre de 2025.",
            "Apresenta planos de ação definidos por área e indicadores acompanhados pela liderança.",
            "Documento de referência para comparativos em ciclos posteriores."),
    ];

    internal static Comunicado ToEntity(CatalogEntry entry, DateTimeOffset seedTime)
    {
        var html = string.Concat(entry.Paragraphs.Select(p => $"<p>{p}</p>"));
        var contentJson = JsonSerializer.Serialize(new Dictionary<string, object?>
        {
            ["html"] = html,
            ["slug"] = entry.Slug,
        });

        return new Comunicado
        {
            Id = entry.Id,
            Slug = entry.Slug,
            Kind = entry.Kind,
            Title = entry.Title,
            Excerpt = entry.Excerpt,
            ContentJson = contentJson,
            AuthorId = entry.AuthorId,
            HeroImageUrl = entry.HeroImageUrl,
            IsMandatory = entry.IsMandatory,
            PublishedAt = entry.PublishedAt,
            ArchivedAt = entry.Kind == ComunicadoKind.Arquivo ? entry.PublishedAt : null,
            CreatedAt = entry.PublishedAt,
            UpdatedAt = entry.PublishedAt,
        };
    }

    internal static IEnumerable<Comunicado> CreateAll(DateTimeOffset seedTime) =>
        Entries.Select(entry => ToEntity(entry, seedTime));
}
