// <auto-generated />
using System;
using LioConecta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LioConecta.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712091200_AddFeedPostScheduledAt")]
    partial class AddFeedPostScheduledAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Snapshot already updated in AppDbContextModelSnapshot.
            // This Designer exists so EF discovers and applies the migration.
#pragma warning restore 612, 618
        }
    }
}
