namespace LioConecta.Application.Common;

public sealed record AppSettingDefinition(
    string Key,
    string Category,
    string Label,
    string? Description,
    string ValueType,
    bool IsSecret,
    string DefaultValue,
    int SortOrder);

public static class AppSettingCatalog
{
    public static IReadOnlyList<AppSettingDefinition> All { get; } =
    [
        new(AppSettingKeys.DatabaseDefaultConnection, "database", "PostgreSQL — connection string",
            "Cadeia de conexão Npgsql usada pela API e workers.", "secret", true,
            "Host=localhost;Port=5433;Database=lioconecta;Username=lioconecta;Password=lioconecta_dev", 1),
        new(AppSettingKeys.RedisConnection, "redis", "Redis — connection string",
            "Backplane SignalR e health check.", "string", false, "localhost:6379", 1),

        new(AppSettingKeys.AzureAdInstance, "azure_ad", "Azure AD — instance URL",
            "Endpoint de login Microsoft.", "string", false, "https://login.microsoftonline.com/", 1),
        new(AppSettingKeys.AzureAdTenantId, "azure_ad", "Azure AD — tenant ID",
            "ID do tenant Entra ID.", "string", false, "", 2),
        new(AppSettingKeys.AzureAdClientId, "azure_ad", "Azure AD — client ID",
            "Application (client) ID. Vazio habilita DevAuth.", "string", false, "", 3),
        new(AppSettingKeys.AzureAdAudience, "azure_ad", "Azure AD — audience",
            "Audience esperada nos tokens JWT.", "string", false, "", 4),

        new(AppSettingKeys.AuthUseDevAuth, "auth", "Permitir DevAuth em desenvolvimento",
            "Quando true, endpoints não exigem autenticação global em Development.", "boolean", false, "true", 1),
        new(AppSettingKeys.AuthProvider, "auth", "Provedor de autenticação",
            "ldap (produção) ou dev (somente desenvolvimento/testes).", "string", false, "ldap", 2),
        new(AppSettingKeys.AuthJwtSigningKey, "auth", "JWT — chave de assinatura",
            "Chave simétrica para tokens do portal. Reinicie a API após alterar.", "secret", true,
            "lioconecta-dev-jwt-signing-key-change-in-production", 3),
        new(AppSettingKeys.AuthJwtExpiryMinutes, "auth", "JWT — expiração (minutos)",
            "Tempo de vida do token emitido no login.", "integer", false, "480", 4),
        new(AppSettingKeys.AuthSuperAdminEmails, "auth", "E-mails LDAP com role Admin",
            "Lista JSON de e-mails corporativos que recebem permissão Admin no login LDAP.", "json", false,
            "[\"leonardo.mendes@liotecnica.com.br\"]", 5),

        new(AppSettingKeys.LdapEnabled, "ldap", "LDAP habilitado",
            "Quando Sim, usuários corporativos autenticam via Active Directory/LDAP.", "boolean", false, "false", 1),
        new(AppSettingKeys.LdapHost, "ldap", "LDAP — servidor",
            "Host ou IP do controlador de domínio (ex.: ad.liotecnica.com.br).", "string", false, "", 2),
        new(AppSettingKeys.LdapPort, "ldap", "LDAP — porta",
            "389 (LDAP) ou 636 (LDAPS).", "integer", false, "389", 3),
        new(AppSettingKeys.LdapUseSsl, "ldap", "LDAP — usar SSL",
            "Habilita LDAPS na porta configurada.", "boolean", false, "false", 4),
        new(AppSettingKeys.LdapBindDn, "ldap", "LDAP — bind DN (conta de serviço)",
            "DN da conta usada para buscas (ex.: CN=svc_lioconecta,OU=Service Accounts,DC=liotecnica,DC=com,DC=br).", "string", false, "", 5),
        new(AppSettingKeys.LdapBindPassword, "ldap", "LDAP — senha da conta de serviço",
            "Senha da conta de bind para buscas e teste de conexão.", "secret", true, "", 6),
        new(AppSettingKeys.LdapSearchBase, "ldap", "LDAP — base de busca",
            "Base DN para localizar usuários (ex.: DC=liotecnica,DC=com,DC=br).", "string", false, "", 7),
        new(AppSettingKeys.LdapUserFilter, "ldap", "LDAP — filtro de usuário",
            "Filtro com placeholder {0} para o login (ex.: (userPrincipalName={0})).", "string", false,
            "(userPrincipalName={0})", 8),
        new(AppSettingKeys.LdapDomain, "ldap", "LDAP — sufixo de domínio",
            "Sufixo UPN quando o login não contém @ (ex.: @liotecnica.com.br).", "string", false,
            "@liotecnica.com.br", 9),

        new(AppSettingKeys.CorsAllowedOrigins, "cors", "Origens CORS permitidas",
            "Lista JSON de URLs do front-end em produção.", "json", false,
            "[\"http://localhost:5173\",\"http://localhost:5174\"]", 1),

        new(AppSettingKeys.TotvsBaseUrl, "totvs", "TOTVS — base URL",
            "URL base da API REST TOTVS.", "string", false, "", 1),
        new(AppSettingKeys.TotvsApiKey, "totvs", "TOTVS — API key",
            "Chave de autenticação TOTVS.", "secret", true, "", 2),

        new(AppSettingKeys.GlpiBaseUrl, "glpi", "GLPI — base URL",
            "URL base da API REST GLPI (ex.: https://servicedesk.liotecnica.com.br/api.php/v1).", "url", false, "", 1),
        new(AppSettingKeys.GlpiPortalUrl, "glpi", "GLPI — portal URL",
            "URL do portal web para links «Ver no GLPI» (ex.: https://servicedesk.liotecnica.com.br).", "url", false,
            "https://servicedesk.liotecnica.com.br", 2),
        new(AppSettingKeys.GlpiAppToken, "glpi", "GLPI — app token (Lioconecta)",
            "App-Token gerado no GLPI para a integração Lioconecta (header App-Token). Não confundir com o user token do usuário de serviço.", "secret", true, "", 3),
        new(AppSettingKeys.GlpiUserToken, "glpi", "GLPI — user token (glpi_system_service)",
            "Remote access key do usuário de serviço glpi_system_service (header Authorization: user_token …).", "secret", true, "", 4),
        new(AppSettingKeys.GlpiProfileId, "glpi", "GLPI — perfil ativo (profiles_id)",
            "ID do perfil após initSession. Use 0 para manter o perfil padrão do usuário de serviço. Se informar um ID que o usuário não possui (ex.: Super-Admin=4), a API ignora e usa o perfil da sessão. Para o token da infra, Gestor=7 costuma funcionar.", "integer", false, "0", 5),
        new(AppSettingKeys.HelpDeskGlpiAreas, "glpi", "Help Desk — áreas do catálogo (JSON)",
            "Lista de áreas exibidas no wizard (como no app mobile): id, name, icon, entityId, categoryRootIds e serviceCount opcional. Área TI com categoryRootIds vazio carrega o catálogo ITIL completo da entidade.", "json", false,
            HelpDeskAreaCatalog.DefaultAreasJson, 6),

        new(AppSettingKeys.GraphTenantId, "graph", "Microsoft Graph — tenant ID",
            "Tenant da app registration Graph.", "string", false, "", 1),
        new(AppSettingKeys.GraphClientId, "graph", "Microsoft Graph — client ID",
            "Client ID da app registration.", "string", false, "", 2),
        new(AppSettingKeys.GraphClientSecret, "graph", "Microsoft Graph — client secret",
            "Secret da app registration.", "secret", true, "", 3),
        new(AppSettingKeys.GraphDirectoryLastSyncUtc, "graph", "Diretório — última sincronização (UTC)",
            "Atualizado automaticamente pelo worker graph-directory-sync.", "string", false, "", 4),

        new(AppSettingKeys.ChatTeamsEnabled, "chat", "Teams Chat — habilitado",
            "Quando Sim, o widget de chat consome conversas reais do Microsoft Teams via Graph.", "boolean", false, "false", 1),
        new(AppSettingKeys.ChatTeamsAuthMode, "chat", "Teams Chat — modo de autenticação",
            "delegated (token por usuário via MSAL) ou application (futuro).", "string", false, "delegated", 2),
        new(AppSettingKeys.ChatTeamsDelegatedScopes, "chat", "Teams Chat — scopes delegados (JSON)",
            "Scopes solicitados no consentimento MSAL (ex.: Chat.ReadWrite, User.Read, offline_access).", "json", false,
            "[\"Chat.ReadWrite\",\"User.Read\",\"offline_access\"]", 3),
        new(AppSettingKeys.ChatTeamsIncludeGroupChats, "chat", "Teams Chat — incluir chats em grupo",
            "Quando Não, lista apenas conversas 1:1.", "boolean", false, "false", 4),
        new(AppSettingKeys.ChatTeamsPollingIntervalSeconds, "chat", "Teams Chat — intervalo de polling (segundos)",
            "Fallback quando SignalR estiver indisponível.", "integer", false, "30", 5),
        new(AppSettingKeys.ChatTeamsSignalREnabled, "chat", "Teams Chat — SignalR habilitado",
            "Broadcast em tempo real de mensagens e atualizações de conversa.", "boolean", false, "true", 6),
        new(AppSettingKeys.ChatTeamsTokenEncryptionKey, "chat", "Teams Chat — chave de criptografia de tokens",
            "Chave simétrica para tokens OAuth delegados armazenados por usuário.", "secret", true, "", 7),
        new(AppSettingKeys.ChatTeamsLastTestUtc, "chat", "Teams Chat — último teste (UTC)",
            "Atualizado automaticamente ao testar a conexão.", "string", false, "", 8),
        new(AppSettingKeys.ChatTeamsLastTestMessage, "chat", "Teams Chat — mensagem do último teste",
            "Atualizado automaticamente ao testar a conexão.", "string", false, "", 9),

        new(AppSettingKeys.PlannerEnabled, "planner", "Planner — integração habilitada",
            "Quando Sim, Minhas Atividades consome tarefas reais do plano Microsoft Planner configurado.", "boolean", false, "false", 1),
        new(AppSettingKeys.PlannerPlanId, "planner", "Planner — ID do plano",
            "GUID do plano da equipe (ex.: plano Teste Leo no Microsoft Planner).", "string", false,
            "i8VPy5W0q0O5Ag52QcdRMWUAH9Yn", 2),
        new(AppSettingKeys.PlannerDefaultBucketId, "planner", "Planner — bucket padrão",
            "Coluna usada ao criar novas tarefas pelo portal. Deixe vazio para usar a primeira coluna do plano.", "string", false, "", 3),
        new(AppSettingKeys.PlannerPlanTitle, "planner", "Planner — título do plano (cache)",
            "Preenchido automaticamente ao testar a conexão.", "string", false, "", 4),
        new(AppSettingKeys.PlannerLastSyncUtc, "planner", "Planner — última validação (UTC)",
            "Atualizado automaticamente ao testar a conexão ou listar tarefas.", "string", false, "", 5),

        new(AppSettingKeys.CalendarEnabled, "calendar", "Calendário Outlook — habilitado",
            "Quando Sim, /calendario consome eventos reais via Microsoft Graph (token delegado por usuário).", "boolean", false, "false", 1),
        new(AppSettingKeys.CalendarDelegatedScopes, "calendar", "Calendário — scopes delegados (JSON)",
            "Scopes MSAL para agenda (ex.: Calendars.ReadWrite, User.Read, offline_access).", "json", false,
            "[\"Calendars.ReadWrite\",\"User.Read\",\"offline_access\"]", 2),
        new(AppSettingKeys.CalendarDefaultView, "calendar", "Calendário — visão padrão",
            "Visão inicial do FullCalendar (dayGridMonth, timeGridWeek, timeGridDay, listWeek).", "string", false, "dayGridMonth", 3),
        new(AppSettingKeys.CalendarShowBirthdays, "calendar", "Calendário — exibir aniversários",
            "Mescla aniversários corporativos na grade.", "boolean", false, "true", 4),
        new(AppSettingKeys.CalendarShowCafeteriaMenu, "calendar", "Calendário — exibir cardápio",
            "Painel lateral com cardápio do refeitório.", "boolean", false, "true", 5),
        new(AppSettingKeys.CalendarMaxParallelCalendars, "calendar", "Calendário — máx. calendários paralelos",
            "Limite de chamadas Graph simultâneas ao buscar calendários secundários.", "integer", false, "8", 6),
        new(AppSettingKeys.CalendarTokenEncryptionKey, "calendar", "Calendário — chave de criptografia de tokens",
            "Chave simétrica para tokens OAuth delegados do Outlook armazenados por usuário.", "secret", true, "", 7),
        new(AppSettingKeys.CalendarLastTestUtc, "calendar", "Calendário — último teste (UTC)",
            "Atualizado automaticamente ao testar a conexão.", "string", false, "", 8),
        new(AppSettingKeys.CalendarLastTestMessage, "calendar", "Calendário — mensagem do último teste",
            "Atualizado automaticamente ao testar a conexão.", "string", false, "", 9),

        new(AppSettingKeys.WorkersTotvsSyncIntervalMinutes, "workers", "Intervalo sync TOTVS (minutos)",
            "Frequência do worker de sincronização TOTVS.", "integer", false, "30", 1),
        new(AppSettingKeys.WorkersGraphSyncIntervalMinutes, "workers", "Intervalo sync Graph (minutos)",
            "Frequência do worker de sincronização Graph.", "integer", false, "60", 2),
        new(AppSettingKeys.WorkersGraphDirectorySyncIntervalMinutes, "workers", "Intervalo sync diretório Graph (minutos)",
            "Frequência do worker graph-directory-sync.", "integer", false, "60", 3),
        new(AppSettingKeys.WorkersTotvsTimesheetSyncIntervalMinutes, "workers", "Intervalo sync ponto TOTVS RM (minutos)",
            "Frequência do worker de cache de espelho de ponto.", "integer", false, "30", 4),
        new(AppSettingKeys.WorkersTotvsTimesheetCacheTtlMinutes, "workers", "TTL cache ponto TOTVS RM (minutos)",
            "Tempo máximo antes de considerar o cache de ponto obsoleto.", "integer", false, "60", 5),
        new(AppSettingKeys.WorkersTotvsPayslipSyncIntervalMinutes, "workers", "Intervalo sync holerite TOTVS RM (minutos)",
            "Frequência do worker de cache de contracheques.", "integer", false, "30", 6),
        new(AppSettingKeys.WorkersTotvsPayslipCacheTtlMinutes, "workers", "TTL cache holerite TOTVS RM (minutos)",
            "Tempo máximo antes de considerar holerites em cache obsoletos.", "integer", false, "60", 7),
        new(AppSettingKeys.WorkersPollClosureIntervalMinutes, "workers", "Intervalo encerramento enquetes (minutos)",
            "Frequência do worker de notificação de enquetes encerradas.", "integer", false, "1", 8),

        new(AppSettingKeys.SerilogDefaultLevel, "serilog", "Nível mínimo de log",
            "Default Serilog (Information, Debug, Warning…).", "string", false, "Information", 1),

        new(AppSettingKeys.MediaComunicadosRootPath, "media", "Comunicados — pasta de armazenamento",
            "Caminho relativo ao ContentRoot ou absoluto para uploads de imagens de destaque.", "string", false,
            "App_Data/media/comunicados", 1),
        new(AppSettingKeys.MediaComunicadosMaxSizeBytes, "media", "Comunicados — tamanho máximo (bytes)",
            "Limite por arquivo enviado no editor de comunicados.", "integer", false, "5242880", 2),
        new(AppSettingKeys.MediaComunicadosAllowedContentTypes, "media", "Comunicados — tipos MIME permitidos",
            "Lista JSON de content-types aceitos no upload.", "json", false,
            "[\"image/jpeg\",\"image/png\",\"image/webp\"]", 3),

        new(AppSettingKeys.MediaPostsRootPath, "media", "Feed — pasta de mídia dos posts",
            "Caminho relativo ao ContentRoot ou absoluto para fotos/vídeos do feed.", "string", false,
            "App_Data/posts/medias", 4),
        new(AppSettingKeys.MediaPostsMaxSizeBytes, "media", "Feed — tamanho máximo (bytes)",
            "Limite por arquivo enviado no composer do feed.", "integer", false, "15728640", 5),
        new(AppSettingKeys.MediaPostsAllowedContentTypes, "media", "Feed — tipos MIME permitidos",
            "Lista JSON de content-types aceitos no upload do feed.", "json", false,
            "[\"image/jpeg\",\"image/png\",\"image/webp\",\"image/gif\",\"video/mp4\",\"video/webm\"]", 6),

        new(AppSettingKeys.MediaPeopleRootPath, "media", "Pessoas — pasta de fotos de perfil",
            "Armazenamento local das fotos baixadas do Microsoft Graph (servidas em /media/people).", "string", false,
            "App_Data/media/people", 7),

        new(AppSettingKeys.ObservabilityOtelEnabled, "observability", "OpenTelemetry habilitado",
            "Exporta traces/metrics via OTLP e endpoint Prometheus.", "boolean", false, "true", 1),
        new(AppSettingKeys.ObservabilityOtelServiceName, "observability", "OTel — service name",
            "Resource service.name nos spans e métricas.", "string", false, "LioConecta.Api", 2),
        new(AppSettingKeys.ObservabilityOtelOtlpEndpoint, "observability", "OTel — OTLP endpoint",
            "URL gRPC do collector Tempo (ex.: http://localhost:4317).", "string", false, "http://localhost:4317", 3),
        new(AppSettingKeys.ObservabilityOtelPrometheusEnabled, "observability", "OTel — Prometheus /metrics",
            "Expõe endpoint /metrics para scrape.", "boolean", false, "true", 4),
        new(AppSettingKeys.ObservabilityOtelTraceSampleRatio, "observability", "OTel — trace sample ratio",
            "Proporção de traces amostrados (0–1).", "string", false, "1.0", 5),

        new(AppSettingKeys.ObservabilityAccessAuditEnabled, "observability", "Access audit habilitado",
            "Registra GET sensíveis e negações de autorização.", "boolean", false, "true", 10),
        new(AppSettingKeys.ObservabilityAccessAuditRoutePatterns, "observability", "Access audit — rotas GET",
            "JSON array { method, pattern, eventName }.", "json", false,
            "[{\"method\":\"GET\",\"pattern\":\"/api/v1/admin/**\",\"eventName\":\"Resource.Viewed\"},{\"method\":\"GET\",\"pattern\":\"/api/v1/rh/**\",\"eventName\":\"Resource.Viewed\"}]",
            11),

        new(AppSettingKeys.ObservabilityPageViewsEnabled, "observability", "Page views habilitado",
            "Aceita batch POST /telemetry/page-views.", "boolean", false, "true", 20),
        new(AppSettingKeys.ObservabilityAuthAuditEnabled, "observability", "Auth audit habilitado",
            "Registra login/logout/falhas JWT.", "boolean", false, "true", 21),

        new(AppSettingKeys.ObservabilityRetentionObservabilityDays, "observability", "Retenção observability (dias)",
            "Purge de observability_events.", "integer", false, "90", 30),
        new(AppSettingKeys.ObservabilityRetentionPageViewDays, "observability", "Retenção page views (dias)",
            "Purge de page_views.", "integer", false, "180", 31),
        new(AppSettingKeys.ObservabilityRetentionAccessEventDays, "observability", "Retenção access events (dias)",
            "Purge de access_events.", "integer", false, "365", 32),
        new(AppSettingKeys.ObservabilityRetentionAggregatesDays, "observability", "Retenção agregados (dias)",
            "Purge de observability_daily_aggregates.", "integer", false, "730", 33),
        new(AppSettingKeys.ObservabilityRetentionEnabled, "observability", "Retenção automática habilitada",
            "Job diário de purge conforme dias configurados.", "boolean", false, "true", 34),
        new(AppSettingKeys.ObservabilityPrivacyIpMode, "observability", "Modo IP (full/hash/both)",
            "O que persistir em eventos de acesso.", "string", false, "both", 35),

        ..BenefitPortalSettingCatalog.ToAppSettingDefinitions(),
        ..LeavePortalSettingCatalog.ToAppSettingDefinitions(),
    ];
}
