using LioConecta.Domain.Enums;

namespace LioConecta.Application.Common;

public record PermissionDefinition(
    string Key,
    BusinessArea Area,
    string Label,
    string Description,
    DataScope[] AllowedScopes,
    string? MenuPath = null);

public static class PermissionCatalog
{
    private static readonly DataScope[] SelfOnly = [DataScope.Self];
    private static readonly DataScope[] SelfGlobal = [DataScope.Self, DataScope.Global];
    private static readonly DataScope[] SelfTeamGlobal = [DataScope.Self, DataScope.Team, DataScope.Global];
    private static readonly DataScope[] TeamGlobal = [DataScope.Team, DataScope.Global];
    private static readonly DataScope[] DeptGlobal = [DataScope.Department, DataScope.Global];
    private static readonly DataScope[] GlobalOnly = [DataScope.Global];

    public static IReadOnlyList<PermissionDefinition> All() =>
    [
        // ── Core ─────────────────────────────────────────────────────────────
        P("portal.access", BusinessArea.Core,
            "Acesso ao portal",
            "Autenticação mínima para navegar no LioConecta (ajuda, mapa do site, notificações).",
            SelfOnly, "/ajuda"),
        P("sitemap.read", BusinessArea.Core,
            "Mapa do site",
            "Visualizar o índice de páginas e rotas do ecossistema LioConecta.",
            SelfOnly, "/mapa-do-site"),
        P("favorites.manage", BusinessArea.Core,
            "Favoritos e atalhos",
            "Gerenciar favoritos, bookmarks e atalhos pessoais.",
            SelfOnly, "/favoritos"),

        // ── Feed & conteúdo social ────────────────────────────────────────────
        P("feed.read", BusinessArea.Core,
            "Feed corporativo",
            "Ler publicações do feed, enquetes, parabenizações e notícias.",
            SelfOnly, "/"),
        P("feed.interact", BusinessArea.Core,
            "Interagir no feed",
            "Curtir, comentar e reagir a publicações do feed.",
            SelfOnly),
        P("feed.manage", BusinessArea.Marketing,
            "Moderar feed",
            "Moderar, publicar e gerenciar conteúdo editorial do feed.",
            GlobalOnly, "/"),
        P("polls.read", BusinessArea.Core,
            "Enquetes",
            "Visualizar e responder enquetes corporativas.",
            SelfOnly, "/enquetes"),
        P("polls.manage", BusinessArea.Marketing,
            "Gerenciar enquetes",
            "Criar, editar e encerrar enquetes.",
            GlobalOnly, "/enquetes"),
        P("celebrations.manage", BusinessArea.Marketing,
            "Parabenizações",
            "Moderar e publicar parabenizações corporativas.",
            GlobalOnly, "/parabenizacoes"),
        P("news.manage", BusinessArea.Marketing,
            "Notícias",
            "Publicar e editar notícias corporativas.",
            GlobalOnly, "/noticias"),

        // ── Comunicados ──────────────────────────────────────────────────────
        P("comunicados.read", BusinessArea.Marketing,
            "Comunicados",
            "Ler comunicados oficiais, departamentais e urgentes.",
            SelfGlobal, "/comunicados"),
        P("comunicados.publish.official", BusinessArea.Marketing,
            "Publicar comunicados oficiais",
            "Criar e publicar comunicados oficiais da empresa.",
            GlobalOnly, "/comunicados/oficiais/novo"),
        P("comunicados.publish.departmental", BusinessArea.Marketing,
            "Publicar comunicados departamentais",
            "Criar comunicados restritos ao departamento do autor.",
            DeptGlobal, "/comunicados/departamentais/novo"),
        P("comunicados.publish.urgent", BusinessArea.Marketing,
            "Publicar comunicados urgentes",
            "Criar comunicados urgentes com destaque imediato.",
            GlobalOnly, "/comunicados/urgentes/novo"),
        P("comunicados.manage", BusinessArea.Marketing,
            "Gerenciar comunicados",
            "Arquivar, editar e administrar o ciclo de vida dos comunicados.",
            GlobalOnly, "/comunicados/arquivo"),

        // ── Pessoas ──────────────────────────────────────────────────────────
        P("people.read", BusinessArea.Pessoas,
            "Diretório de pessoas",
            "Consultar diretório, aniversariantes e novos colaboradores.",
            SelfGlobal, "/pessoas/diretorio"),
        P("people.profile.read", BusinessArea.Pessoas,
            "Perfis de colaboradores",
            "Visualizar perfis completos de colaboradores.",
            SelfTeamGlobal, "/pessoas/perfil"),
        P("people.salary.read", BusinessArea.RH,
            "Dados salariais",
            "Visualizar informações salariais em perfis de colaboradores.",
            SelfTeamGlobal),

        // ── Organograma ──────────────────────────────────────────────────────
        P("org_chart.view", BusinessArea.Pessoas,
            "Organograma",
            "Visualizar organograma corporativo (visão padrão).",
            SelfGlobal, "/pessoas/organograma"),
        P("org_chart.view_full", BusinessArea.Pessoas,
            "Organograma completo",
            "Visualizar organograma com dados sensíveis e visão expandida.",
            GlobalOnly, "/pessoas/organograma"),
        P("org_chart.edit", BusinessArea.Pessoas,
            "Editar organograma",
            "Editar estrutura e vínculos do organograma.",
            GlobalOnly, "/admin/governanca/organograma"),
        P("org_chart.govern", BusinessArea.Pessoas,
            "Governança do organograma",
            "Configurar regras de governança e aprovações do organograma.",
            GlobalOnly, "/admin/governanca/organograma"),

        // ── Ramais ───────────────────────────────────────────────────────────
        P("ramais.read", BusinessArea.Pessoas,
            "Ramais",
            "Consultar lista telefônica e ramais corporativos.",
            SelfGlobal, "/pessoas/ramais"),
        P("ramais.manage", BusinessArea.TI,
            "Gerenciar ramais",
            "Cadastrar, editar e remover ramais e extensões.",
            GlobalOnly, "/pessoas/ramais"),

        // ── Grupos ───────────────────────────────────────────────────────────
        P("groups.read", BusinessArea.Core,
            "Grupos",
            "Visualizar grupos corporativos e participar de grupos.",
            SelfOnly, "/grupos/meus-grupos"),
        P("groups.create", BusinessArea.Core,
            "Criar grupos",
            "Solicitar criação de novos grupos corporativos.",
            SelfOnly, "/grupos/criar"),
        P("groups.approve", BusinessArea.Plataforma,
            "Aprovar grupos",
            "Aprovar ou rejeitar solicitações de criação de grupos.",
            GlobalOnly, "/grupos/aprovacoes"),

        // ── Documentos ───────────────────────────────────────────────────────
        P("documents.read", BusinessArea.Core,
            "Biblioteca de documentos",
            "Consultar biblioteca, formulários, manuais e políticas.",
            SelfGlobal, "/documentos"),
        P("documents.manage", BusinessArea.Juridico,
            "Gerenciar documentos",
            "Publicar, editar e arquivar documentos corporativos e políticas internas.",
            GlobalOnly, "/documentos/politicas-internas"),

        // ── Calendário ───────────────────────────────────────────────────────
        P("calendar.read", BusinessArea.Core,
            "Calendário",
            "Visualizar eventos e agenda corporativa.",
            SelfOnly, "/calendario"),
        P("calendar.manage", BusinessArea.Core,
            "Gerenciar calendário",
            "Criar e editar eventos no calendário corporativo.",
            SelfGlobal, "/calendario"),

        // ── RH — Benefícios ──────────────────────────────────────────────────
        P("benefits.read", BusinessArea.RH,
            "Benefícios",
            "Consultar catálogo e adesão aos benefícios corporativos.",
            SelfOnly, "/servicos/beneficios"),
        P("benefits.manage", BusinessArea.RH,
            "Gerenciar benefícios",
            "Administrar catálogo, elegibilidade e gestão de benefícios.",
            GlobalOnly, "/servicos/beneficios/gestao"),

        // ── RH — Contracheque ────────────────────────────────────────────────
        P("payslips.read", BusinessArea.RH,
            "Contracheque",
            "Visualizar holerites e demonstrativos de pagamento.",
            SelfTeamGlobal, "/servicos/contracheque"),

        // ── RH — Férias e ausências ──────────────────────────────────────────
        P("leave.read", BusinessArea.RH,
            "Férias e ausências",
            "Consultar saldo e histórico de férias e ausências.",
            SelfOnly, "/servicos/ferias-ausencias"),
        P("leave.request", BusinessArea.RH,
            "Solicitar férias",
            "Abrir solicitações de férias e ausências.",
            SelfOnly, "/servicos/ferias-ausencias"),
        P("leave.manage", BusinessArea.RH,
            "Gerenciar férias",
            "Administrar solicitações e saldos de férias da equipe ou corporação.",
            GlobalOnly, "/servicos/ferias-ausencias/gestao"),
        P("leave.approve", BusinessArea.RH,
            "Aprovar férias",
            "Aprovar ou rejeitar solicitações de férias e ausências.",
            TeamGlobal, "/servicos/ferias-ausencias/gestao"),
        P("leave.notify", BusinessArea.RH,
            "Notificações de férias",
            "Receber e gerenciar notificações de férias e ausências.",
            GlobalOnly),

        // ── RH — Ponto eletrônico ────────────────────────────────────────────
        P("ponto.read", BusinessArea.RH,
            "Ponto eletrônico",
            "Consultar espelho de ponto e registros de jornada.",
            SelfOnly, "/servicos/ponto-eletronico"),
        P("ponto.manage", BusinessArea.RH,
            "Gerenciar ponto",
            "Administrar ajustes e gestão operacional de ponto.",
            GlobalOnly, "/servicos/ponto-eletronico"),
        P("ponto.admin", BusinessArea.RH,
            "Administrar ponto TOTVS",
            "Sincronização e administração avançada de ponto via TOTVS RM.",
            GlobalOnly, "/admin/totvs-rm"),

        // ── RH — Solicitações ────────────────────────────────────────────────
        P("rh_requests.read", BusinessArea.RH,
            "Solicitações RH",
            "Consultar solicitações de recursos humanos.",
            SelfOnly, "/servicos/solicitacoes-rh"),
        P("rh_requests.manage", BusinessArea.RH,
            "Gerenciar solicitações RH",
            "Atender, aprovar e administrar solicitações de RH.",
            GlobalOnly, "/servicos/solicitacoes-rh"),

        // ── RH — Vale-transporte ─────────────────────────────────────────────
        P("transport.read", BusinessArea.RH,
            "Vale-transporte",
            "Consultar informações de vale-transporte.",
            SelfOnly, "/servicos/vale-transporte"),
        P("transport.manage", BusinessArea.RH,
            "Gerenciar vale-transporte",
            "Administrar benefício de vale-transporte.",
            GlobalOnly, "/servicos/vale-transporte"),

        // ── Financeiro operacional ───────────────────────────────────────────
        P("reimbursement.read", BusinessArea.Financeiro,
            "Reembolso de despesas",
            "Consultar solicitações de reembolso de despesas.",
            SelfGlobal, "/servicos/reembolso-despesas"),
        P("reimbursement.manage", BusinessArea.Financeiro,
            "Gerenciar reembolsos",
            "Aprovar, processar e administrar reembolsos de despesas.",
            GlobalOnly, "/servicos/reembolso-despesas"),
        P("travel_advance.read", BusinessArea.Financeiro,
            "Adiantamento de viagem",
            "Consultar solicitações de adiantamento de viagem.",
            SelfGlobal, "/servicos/adiantamento-viagem"),
        P("travel_advance.manage", BusinessArea.Financeiro,
            "Gerenciar adiantamentos",
            "Aprovar e administrar adiantamentos de viagem.",
            GlobalOnly, "/servicos/adiantamento-viagem"),

        // ── TI — Help Desk ───────────────────────────────────────────────────
        P("helpdesk.read", BusinessArea.TI,
            "Help Desk",
            "Abrir e acompanhar chamados de suporte de TI.",
            SelfOnly, "/servicos/help-desk"),
        P("helpdesk.manage", BusinessArea.TI,
            "Gerenciar Help Desk",
            "Administrar chamados, filas e atendimento de suporte de TI.",
            GlobalOnly, "/servicos/ti"),

        // ── TI — Sistemas ────────────────────────────────────────────────────
        P("systems.read", BusinessArea.TI,
            "Catálogo de sistemas",
            "Consultar catálogo de sistemas e acessos corporativos.",
            SelfGlobal, "/servicos/acesso-sistemas"),
        P("systems.manage", BusinessArea.TI,
            "Gerenciar sistemas",
            "Administrar catálogo de sistemas e permissões de acesso.",
            GlobalOnly, "/servicos/acesso-sistemas"),

        // ── TI — Equipamentos e VPN ──────────────────────────────────────────
        P("equipment.request", BusinessArea.TI,
            "Solicitar equipamento",
            "Abrir solicitações de equipamentos de TI.",
            SelfOnly, "/servicos/solicitar-equipamento"),
        P("equipment.manage", BusinessArea.TI,
            "Gerenciar equipamentos",
            "Administrar solicitações e inventário de equipamentos.",
            GlobalOnly, "/servicos/solicitar-equipamento"),
        P("vpn.read", BusinessArea.TI,
            "VPN",
            "Consultar informações e status de acesso VPN.",
            SelfGlobal, "/servicos/vpn-acesso-remoto"),
        P("vpn.manage", BusinessArea.TI,
            "Gerenciar VPN",
            "Administrar acessos e credenciais VPN.",
            GlobalOnly, "/servicos/vpn-acesso-remoto"),

        // ── Facilities ───────────────────────────────────────────────────────
        P("facilities.request", BusinessArea.Facilities,
            "Solicitar serviços Facilities",
            "Abrir solicitações de serviços prediais e facilities.",
            SelfOnly, "/servicos/facilities"),
        P("facilities.rooms.manage", BusinessArea.Facilities,
            "Reserva de salas",
            "Administrar reservas e disponibilidade de salas.",
            GlobalOnly, "/servicos/reservas-salas"),
        P("facilities.vehicles.manage", BusinessArea.Facilities,
            "Reserva de veículos",
            "Administrar frota e reservas de veículos corporativos.",
            GlobalOnly, "/servicos/reserva-veiculos"),
        P("facilities.badge.manage", BusinessArea.Facilities,
            "Crachá de visitantes",
            "Gerenciar emissão de crachás e controle de visitantes.",
            GlobalOnly, "/servicos/cracha-visitantes"),
        P("facilities.mail.manage", BusinessArea.Facilities,
            "Encomendas e correios",
            "Administrar recebimento e entrega de encomendas.",
            GlobalOnly, "/servicos/encomendas-correios"),
        P("facilities.cleaning.manage", BusinessArea.Facilities,
            "Limpeza",
            "Gerenciar solicitações e serviços de limpeza.",
            GlobalOnly, "/servicos/limpeza"),
        P("facilities.maintenance.manage", BusinessArea.Facilities,
            "Manutenção predial",
            "Administrar chamados de manutenção predial.",
            GlobalOnly, "/servicos/manutencao-predial"),
        P("facilities.printing.manage", BusinessArea.Facilities,
            "Copiadora e impressão",
            "Gerenciar serviços de copiadora e impressão.",
            GlobalOnly, "/servicos/copiadora"),
        P("facilities.parking.manage", BusinessArea.Facilities,
            "Estacionamento",
            "Administrar vagas e controle de estacionamento.",
            GlobalOnly, "/servicos/estacionamento"),
        P("facilities.cafeteria.read", BusinessArea.Facilities,
            "Refeitório",
            "Consultar informações do refeitório corporativo.",
            SelfGlobal, "/servicos/refeitorio"),
        P("facilities.menu.edit", BusinessArea.Facilities,
            "Cardápio",
            "Editar cardápio e menu do refeitório.",
            GlobalOnly, "/servicos/cardapio"),
        P("facilities.hvac.manage", BusinessArea.Facilities,
            "Climatização",
            "Gerenciar solicitações de climatização e ar-condicionado.",
            GlobalOnly, "/servicos/climatizacao"),
        P("facilities.waste.manage", BusinessArea.Facilities,
            "Gestão de resíduos",
            "Administrar coleta e gestão de resíduos.",
            GlobalOnly, "/servicos/gestao-residuos"),

        // ── Jurídico ─────────────────────────────────────────────────────────
        P("legal.request", BusinessArea.Juridico,
            "Solicitar serviços jurídicos",
            "Abrir solicitações de serviços do departamento jurídico.",
            SelfOnly, "/servicos/juridico"),
        P("legal.certificates.manage", BusinessArea.Juridico,
            "Declarações e certidões",
            "Administrar declarações, certidões e documentos legais.",
            GlobalOnly, "/servicos/declaracoes-certidoes"),
        P("legal.signature.manage", BusinessArea.Juridico,
            "Assinatura digital",
            "Gerenciar fluxos de assinatura digital.",
            GlobalOnly, "/servicos/assinatura-digital"),
        P("legal.insurance.manage", BusinessArea.Juridico,
            "Seguro de vida",
            "Administrar seguro de vida corporativo.",
            GlobalOnly, "/servicos/seguro-vida"),
        P("legal.whistleblower.manage", BusinessArea.Juridico,
            "Canal de denúncias",
            "Administrar canal de denúncias e ocorrências.",
            GlobalOnly, "/servicos/canal-denuncias"),
        P("legal.contracts.manage", BusinessArea.Juridico,
            "Contratos e minutas",
            "Gerenciar contratos, minutas e revisões jurídicas.",
            GlobalOnly, "/servicos/contratos-minutas"),
        P("legal.lgpd.manage", BusinessArea.Juridico,
            "LGPD e privacidade",
            "Administrar solicitações e conformidade LGPD.",
            GlobalOnly, "/servicos/lgpd-privacidade"),
        P("legal.conduct.manage", BusinessArea.Juridico,
            "Código de conduta",
            "Gerenciar código de conduta e compliance ético.",
            GlobalOnly, "/servicos/codigo-conduta"),
        P("legal.diligence.manage", BusinessArea.Juridico,
            "Due diligence",
            "Administrar processos de due diligence.",
            GlobalOnly, "/servicos/due-diligence"),
        P("legal.powers.manage", BusinessArea.Juridico,
            "Procurações",
            "Gerenciar procurações e poderes legais.",
            GlobalOnly, "/servicos/procuracoes"),
        P("legal.advisory.manage", BusinessArea.Juridico,
            "Consultoria jurídica",
            "Administrar consultas e pareceres jurídicos.",
            GlobalOnly, "/servicos/consultoria-juridica"),

        // ── Loop (Projetos) ──────────────────────────────────────────────────
        P("loop.access", BusinessArea.Projetos,
            "Acesso ao Loop",
            "Acessar o módulo Loop de gestão de projetos.",
            GlobalOnly, "/loop"),
        P("loop.manage", BusinessArea.Projetos,
            "Gerenciar Loop",
            "Criar, editar e administrar projetos no Loop.",
            GlobalOnly, "/loop"),
        P("loop.approve", BusinessArea.Projetos,
            "Aprovar Loop",
            "Aprovar solicitações e entregas no fluxo do Loop.",
            GlobalOnly, "/loop/aprovacoes"),

        // ── Pulse (Projetos) ─────────────────────────────────────────────────
        P("pulse.access", BusinessArea.Projetos,
            "Acesso ao Pulse",
            "Acessar o módulo Pulse de squads ágeis.",
            GlobalOnly, "/pulse"),
        P("pulse.manage", BusinessArea.Projetos,
            "Gerenciar Pulse",
            "Administrar sprints, boards e squads no Pulse.",
            GlobalOnly, "/pulse"),

        // ── Compass (Contábil / Planejamento) ────────────────────────────────
        P("compass.access", BusinessArea.Planejamento,
            "Acesso ao Compass",
            "Entrar no módulo Compass de planejamento integrado.",
            GlobalOnly, "/compass"),
        P("compass.read", BusinessArea.Planejamento,
            "Compass — leitura",
            "Visualizar dashboards, volume, canais e análises operacionais.",
            GlobalOnly, "/compass/volume"),
        P("compass.manage", BusinessArea.Planejamento,
            "Compass — gestão",
            "Administrar ciclo IBP, reuniões e cadastros do Compass.",
            GlobalOnly, "/compass/ciclo"),
        P("compass.financial.read", BusinessArea.Contabil,
            "Compass — financeiro",
            "Visualizar P&L, análise YTD e dados financeiros Hyperion.",
            GlobalOnly, "/compass/financeiro"),
        P("compass.financial.reconcile", BusinessArea.Contabil,
            "Compass — reconciliação",
            "Executar reconciliação financeira no Compass.",
            GlobalOnly, "/compass/reconciliacao"),
        P("compass.export", BusinessArea.Contabil,
            "Compass — exportar",
            "Exportar dados e relatórios do Compass.",
            GlobalOnly),
        P("compass.scenarios.manage", BusinessArea.Planejamento,
            "Compass — cenários",
            "Criar e gerenciar cenários de planejamento.",
            GlobalOnly, "/compass/cenarios"),
        P("compass.decisions.manage", BusinessArea.Planejamento,
            "Compass — decisões",
            "Registrar e gerenciar decisões de planejamento.",
            GlobalOnly, "/compass/decisoes"),

        // ── Admin / Plataforma ───────────────────────────────────────────────
        P("admin.settings.manage", BusinessArea.Plataforma,
            "Configurações do backend",
            "Administrar configurações globais da plataforma e integrações.",
            GlobalOnly, "/admin/configuracoes-backend"),
        P("admin.workers.manage", BusinessArea.Plataforma,
            "Workers",
            "Monitorar e gerenciar workers em background.",
            GlobalOnly, "/admin/workers"),
        P("admin.email.manage", BusinessArea.Plataforma,
            "E-mail SMTP",
            "Configurar envio de e-mail e templates SMTP.",
            GlobalOnly, "/admin/email"),
        P("admin.totvs.manage", BusinessArea.Plataforma,
            "Integração TOTVS",
            "Administrar integração TOTVS RM na plataforma.",
            GlobalOnly, "/admin/totvs-rm"),
        P("admin.integrations.test", BusinessArea.Plataforma,
            "Testar integrações",
            "Executar testes de LDAP, Graph, GLPI e demais integrações.",
            GlobalOnly, "/admin/configuracoes-backend"),
        P("admin.ldap.test", BusinessArea.Plataforma,
            "Testar LDAP",
            "Executar testes de conexão e autenticação LDAP.",
            GlobalOnly, "/admin/configuracoes-backend"),

        // ── Analytics & Auditoria ────────────────────────────────────────────
        P("analytics.view", BusinessArea.Analytics,
            "Analytics",
            "Visualizar dashboards de analytics e observabilidade.",
            GlobalOnly, "/analytics"),
        P("analytics.export", BusinessArea.Analytics,
            "Exportar analytics",
            "Exportar dados e relatórios de analytics.",
            GlobalOnly, "/analytics"),
        P("audit.view", BusinessArea.Analytics,
            "Trilha de auditoria",
            "Consultar trilha de auditoria e eventos de acesso.",
            GlobalOnly, "/admin/trilha-auditoria"),
        P("audit.export", BusinessArea.Analytics,
            "Exportar auditoria",
            "Exportar registros da trilha de auditoria.",
            GlobalOnly, "/admin/trilha-auditoria"),

        // ── Quiosque ─────────────────────────────────────────────────────────
        P("kiosk.read", BusinessArea.Quiosque,
            "Modo quiosque",
            "Exibir feed e comunicados em telas compartilhadas.",
            GlobalOnly, "/quiosque"),
        P("kiosk.display", BusinessArea.Quiosque,
            "Display quiosque",
            "Controlar exibição em modo totem/display.",
            GlobalOnly, "/quiosque"),
        P("kiosk.content.manage", BusinessArea.Marketing,
            "Curadoria quiosque",
            "Selecionar e curar conteúdo exibido no quiosque.",
            GlobalOnly, "/quiosque"),

        // ── RBAC ─────────────────────────────────────────────────────────────
        P("rbac.roles.manage", BusinessArea.Plataforma,
            "Gerenciar roles",
            "Criar, editar e excluir roles e matriz de permissões.",
            GlobalOnly, "/admin/controle-acesso"),
        P("rbac.test_users.manage", BusinessArea.Plataforma,
            "Usuários de teste",
            "Criar e administrar key users e contas de teste.",
            GlobalOnly, "/admin/controle-acesso"),
        P("rbac.assignments.manage", BusinessArea.Plataforma,
            "Atribuições RBAC",
            "Atribuir e revogar roles em colaboradores e portal users.",
            GlobalOnly, "/admin/controle-acesso"),

        // ── Atividades ───────────────────────────────────────────────────────
        P("activities.read", BusinessArea.Core,
            "Minhas atividades",
            "Visualizar atividades e tarefas pendentes.",
            SelfOnly, "/minhas-atividades"),
        P("activities.manage", BusinessArea.Projetos,
            "Gerenciar atividades",
            "Administrar atividades corporativas e delegações.",
            SelfTeamGlobal, "/minhas-atividades"),

        // ── UniLio LMS ───────────────────────────────────────────────────────
        P("unilio.access", BusinessArea.UniLio,
            "Acesso UniLio",
            "Porta de entrada do módulo UniLio no portal.",
            SelfOnly, "/unilio"),
        P("unilio.learn.read", BusinessArea.UniLio,
            "UniLio — aprendizagem",
            "Acessar catálogo, trilhas, player e dashboard do aluno.",
            SelfOnly, "/unilio/catalogo"),
        P("unilio.learn.assess", BusinessArea.UniLio,
            "UniLio — avaliações",
            "Realizar quizzes e avaliações de cursos.",
            SelfOnly, "/unilio/avaliacoes"),
        P("unilio.learn.certificates", BusinessArea.UniLio,
            "UniLio — certificados",
            "Visualizar certificados de conclusão próprios.",
            SelfOnly, "/unilio/certificados"),
        P("unilio.compliance.read", BusinessArea.UniLio,
            "UniLio — compliance",
            "Consultar treinamentos obrigatórios e status de compliance.",
            SelfOnly, "/unilio/compliance"),
        P("unilio.compliance.manage", BusinessArea.UniLio,
            "UniLio — gestão compliance",
            "Atribuir e monitorar compliance corporativo de treinamentos.",
            GlobalOnly, "/unilio/compliance"),
        P("unilio.community.read", BusinessArea.UniLio,
            "UniLio — comunidade",
            "Ler feed e conteúdos da comunidade de aprendizagem.",
            SelfOnly, "/unilio/comunidade"),
        P("unilio.community.post", BusinessArea.UniLio,
            "UniLio — publicar comunidade",
            "Publicar posts e interagir na comunidade UniLio.",
            SelfOnly, "/unilio/comunidade"),
        P("unilio.events.read", BusinessArea.UniLio,
            "UniLio — eventos",
            "Visualizar eventos, lives e calendário de aprendizagem.",
            SelfOnly, "/unilio/eventos"),
        P("unilio.events.register", BusinessArea.UniLio,
            "UniLio — inscrição eventos",
            "Inscrever-se em eventos e lives corporativas.",
            SelfOnly, "/unilio/eventos"),
        P("unilio.skills.read", BusinessArea.UniLio,
            "UniLio — competências",
            "Consultar mapa de competências e skills próprias.",
            SelfOnly, "/unilio/competencias"),
        P("unilio.skills.manage", BusinessArea.UniLio,
            "UniLio — gestão competências",
            "Administrar matriz corporativa de competências.",
            GlobalOnly, "/unilio/competencias"),
        P("unilio.recommendations.read", BusinessArea.UniLio,
            "UniLio — recomendações",
            "Receber recomendações personalizadas de cursos.",
            SelfOnly, "/unilio/recomendacoes"),
        P("unilio.instructor.panel", BusinessArea.UniLio,
            "UniLio — painel instrutor",
            "Acessar painel e ferramentas do instrutor.",
            SelfOnly, "/unilio/instrutor"),
        P("unilio.courses.author", BusinessArea.UniLio,
            "UniLio — autorar cursos",
            "Criar cursos e conteúdos em rascunho.",
            SelfOnly, "/unilio/instrutor"),
        P("unilio.courses.edit.own", BusinessArea.UniLio,
            "UniLio — editar cursos próprios",
            "Editar cursos onde o usuário é instrutor responsável.",
            SelfOnly, "/unilio/instrutor"),
        P("unilio.courses.approve", BusinessArea.UniLio,
            "UniLio — aprovar cursos",
            "Aprovar ou rejeitar cursos na fila de publicação.",
            GlobalOnly, "/unilio/admin/aprovacoes"),
        P("unilio.courses.publish", BusinessArea.UniLio,
            "UniLio — publicar cursos",
            "Publicar cursos aprovados ou diretamente no catálogo.",
            GlobalOnly, "/unilio/admin/aprovacoes"),
        P("unilio.team.view", BusinessArea.UniLio,
            "UniLio — meu time",
            "Visualizar progresso de aprendizagem dos subordinados.",
            TeamGlobal, "/unilio/gestor"),
        P("unilio.reports.view", BusinessArea.UniLio,
            "UniLio — relatórios",
            "Acessar relatórios executivos de aprendizagem.",
            TeamGlobal, "/unilio/relatorios"),
        P("unilio.paths.manage", BusinessArea.UniLio,
            "UniLio — trilhas",
            "Criar e gerenciar trilhas de aprendizagem corporativas.",
            GlobalOnly, "/unilio/trilhas"),
    ];

    private static PermissionDefinition P(
        string key,
        BusinessArea area,
        string label,
        string description,
        DataScope[] allowedScopes,
        string? menuPath = null) =>
        new(key, area, label, description, allowedScopes, menuPath);
}
